2025-05-02 11:18:18,171 INFO: [PID 647643] start_node.py script started. Logging configured.
2025-05-02 11:18:18,172 INFO: [PID 647643] symlinked /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_0/data/data â†’ /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_0/data
2025-05-02 11:18:18,698 INFO: [PID 647675] Blockchain object __init__ called.
2025-05-02 11:18:18,919 INFO: [PID 647675] Blockchain initialized for port 9000. Lock object received: <class 'multiprocessing.managers.AcquirerProxy'>
2025-05-02 11:18:18,922 INFO: [PID 647675] Entering setup_node()
2025-05-02 11:18:18,955 INFO: [PID 647675] [Node Setup] No existing blockchain found. Waiting...
2025-05-02 11:18:18,980 INFO: Serving on http://127.0.0.1:5900
2025-05-02 11:18:20,960 INFO: [Startup] Node 0 initiating sync with peers...
2025-05-02 11:18:20,961 INFO: [PID 647675] [Startup] Node 0 initiating sync with peers...
2025-05-02 11:18:21,020 INFO: [PID 647675] [Startup] Starting download from peer 9001 (binding local 8000)...
2025-05-02 11:18:21,020 INFO: [PID 647675] [Downloader] Starting download from 8000 :9001...
2025-05-02 11:18:21,025 INFO: [PID 647675] [Downloader] No local blocks found. Requesting from Genesis.
2025-05-02 11:18:21,026 INFO: [PID 647675] Node connect: Connecting to ('127.0.0.1', 9001)...
2025-05-02 11:18:21,026 INFO: [PID 647675] Node connect: Connected successfully to ('127.0.0.1', 9001)
2025-05-02 11:18:21,026 INFO: [PID 647675] [connectToHost] Successfully connected to 9001.
2025-05-02 11:18:21,026 INFO: [PID 647675] [Downloader] Sent requestBlock to 8000:9001
2025-05-02 11:18:21,087 INFO: [PID 647675] [Downloader 9001] Received portlist: [9000, 9001, 9002]
2025-05-02 11:18:21,090 INFO: [PID 647675] [Downloader 9001] Received FinishedSending. Download complete.
2025-05-02 11:18:21,090 INFO: [PID 647675] [Downloader] Connection to 8000:9001 closed.
2025-05-02 11:18:21,091 INFO: [PID 647675] [Startup] Starting download from peer 9002 (binding local 8000)...
2025-05-02 11:18:21,092 INFO: [PID 647675] [Downloader] Starting download from 8000 :9002...
2025-05-02 11:18:21,096 INFO: [PID 647675] [Downloader] No local blocks found. Requesting from Genesis.
2025-05-02 11:18:21,096 INFO: [PID 647675] Node connect: Connecting to ('127.0.0.1', 9002)...
2025-05-02 11:18:21,096 ERROR: [PID 647675] Node connect: Failed to connect to ('127.0.0.1', 9002): [Errno 111] Connection refused
2025-05-02 11:18:21,096 ERROR: [PID 647675] [connectToHost] Failed to connect to 9002 (Node.connect returned None).
2025-05-02 11:18:21,096 INFO: [PID 647675] [Downloader] Connection to 8000:9002 closed.
2025-05-02 11:18:21,096 INFO: [PID 647675] [Startup] Node 0 initial sync process finished.
2025-05-02 11:18:21,098 INFO: [Startup] Node 0 initial sync process finished.
2025-05-02 11:18:22,770 INFO: Node acceptConnection: Accepted connection from ('127.0.0.1', 38736)
2025-05-02 11:18:24,200 INFO: Node acceptConnection: Accepted connection from ('127.0.0.1', 38740)
2025-05-02 11:18:24,801 INFO: Node acceptConnection: Accepted connection from ('127.0.0.1', 38752)
2025-05-02 11:18:24,998 INFO: Node acceptConnection: Accepted connection from ('127.0.0.1', 38760)
2025-05-02 11:18:25,006 INFO: Node acceptConnection: Accepted connection from ('127.0.0.1', 38766)
2025-05-02 11:18:25,017 ERROR: Node read: Error during parse() on accepted socket fd=15: Connection closed before magic bytes received
Traceback (most recent call last):
  File "/dcs/project/algoblock/MainCode/PoSBlockchain/code_node2/Blockchain/Backend/core/network/connection.py", line 266, in read
    envelope = NetworkEnvelope.parse(self.stream)
  File "/dcs/project/algoblock/MainCode/PoSBlockchain/code_node2/Blockchain/Backend/core/network/network.py", line 23, in parse
    raise RuntimeError("Connection closed before magic bytes received")
RuntimeError: Connection closed before magic bytes received
2025-05-02 11:18:25,029 INFO: [Handler from ('127.0.0.1', 38766)] Read returned None (timeout or connection closed). Ending handler.
Exception ignored in: <function BaseDB.__del__ at 0x7f11c1ef0790>
Traceback (most recent call last):
  File "/dcs/project/algoblock/MainCode/PoSBlockchain/code_node2/Blockchain/Backend/core/database/db.py", line 129, in __del__
    self.conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139714145285696 and this is thread id 139714136892992.
